
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from gauss_gui import open_gauss_quad
from romberg import open_romberg_gui
from derivadaparcial import open_partial_derivative_window
from derivadaPuntoFijo import open_single_derivative
from Simpson import open_simpson_window

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("565x518")
window.configure(bg = "#F7FDFD")
window.title("Menu: Stephensen Methodverse Of Madness")

canvas = Canvas(
    window,
    bg = "#F7FDFD",
    height = 518,
    width = 565,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    182.0,
    102.0,
    anchor="nw",
    text="Diferencias centrales",
    fill="#000000",
    font=("Inter Bold", 19 * -1)
)

canvas.create_text(
    165.0,
    266.0,
    anchor="nw",
    text="Metodos de integracion",
    fill="#000000",
    font=("Inter Bold", 19 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
partial_derivative_button = Button(
    window,
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_partial_derivative_window(window),
    relief="flat"
)
partial_derivative_button.place(
    x=307.99639892578125,
    y=144.0,
    width=187.65342712402344,
    height=49.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
single_derivative_button = Button(
    window,
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_single_derivative(window),
    relief="flat"
)
single_derivative_button.place(
    x=64.25091552734375,
    y=144.0,
    width=187.65342712402344,
    height=49.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
romberg_button = Button(
    window,
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_romberg_gui(window),
    relief="flat"
)
romberg_button.place(
    x=186.63357543945312,
    y=411.0,
    width=187.65342712402344,
    height=49.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
quadrature_button = Button(
    window,
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_gauss_quad(window),
    relief="flat"
)
quadrature_button.place(
    x=307.99639892578125,
    y=317.0,
    width=187.65342712402344,
    height=49.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
simpson_button = Button(
    window,
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_simpson_window(window),
    relief="flat"
)
simpson_button.place(
    x=65.270751953125,
    y=317.0,
    width=187.65342712402344,
    height=49.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    565.0,
    56.0,
    fill="#10ABC0",
    outline="")

canvas.create_text(
    159.0,
    17.0,
    anchor="nw",
    text="Metodos numericos",
    fill="#FFFFFF",
    font=("Inter Bold", 25 * -1)
)
window.resizable(False, False)
window.mainloop()
